name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: 10.x
      - name: Install NBGV tool
        run: dotnet tool install --tool-path . nbgv
      - name: Set Version
        run: ./nbgv cloud
      - name: Create Packages
        run: dotnet pack -c Release -o packages -p:ContinuousIntegrationBuild=true
      - name: Push packages to NuGet.org
        run: dotnet nuget push ./packages/Docker.DotNet.*.nupkg --skip-duplicate -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      - name: Create Release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            return github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: tag,
              draft: false,
              prerelease: false,
              generate_release_notes: true
            })
